entrypoint: bundle exec rackup --port $PORT
env: flex
runtime: ruby

env_variables:
  SECRET_KEY_BASE: SECRET_KEY_BASE
  IBLUE_DATABASE_PASSWORD: IBLUE_DATABASE_PASSWORD

beta_settings:
  cloud_sql_instances: iblue2:europe-west2:iblue